const data = {
    items: [
        { 
            id: 1, 
            name: 'JavaScript', 
            categoryId: 1, 
            levelId: 1, 
            popularity: 10, 
            year: 1995, 
            img: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png', 
            description: 'Linguagem de programação amplamente utilizada para desenvolvimento web frontend e backend.', 
        },
        { 
            id: 2, 
            name: 'Python', 
            categoryId: 1, 
            levelId: 1, 
            popularity: 10, 
            year: 1991, 
            img: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg', 
            description: 'Linguagem versátil usada em ciência de dados, automação, IA e desenvolvimento web.', 
        },
        { 
            id: 3, 
            name: 'React', 
            categoryId: 2, 
            levelId: 2, 
            popularity: 9, 
            year: 2013, 
            img: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg', 
            description: 'Biblioteca JavaScript para construção de interfaces de usuário baseada em componentes.', 
        },
        { 
            id: 4, 
            name: 'Node.js', 
            categoryId: 3, 
            levelId: 2, 
            popularity: 9, 
            year: 2009, 
            img: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Node.js_logo.svg', 
            description: 'Ambiente de execução JavaScript server-side.', 
        },
        { 
            id: 5, 
            name: 'Docker', 
            categoryId: 4, 
            levelId: 3, 
            popularity: 8, 
            year: 2013, 
            img: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Docker_%28container_engine%29_logo.svg', 
            description: 'Plataforma para criação e execução de containers.', 
        },
        { 
            id: 6, 
            name: 'PostgreSQL', 
            categoryId: 5, 
            levelId: 2, 
            popularity: 8, 
            year: 1996, 
            img: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg', 
            description: 'Sistema gerenciador de banco de dados relacional open source.', 
        },
        { 
            id: 7, 
            name: 'TensorFlow', 
            categoryId: 6, 
            levelId: 4, 
            popularity: 7, 
            year: 2015, 
            img: 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg', 
            description: 'Biblioteca open source para machine learning desenvolvida pelo Google.', 
        },
        { 
            id: 8, 
            name: 'TypeScript', 
            categoryId: 1, 
            levelId: 2, 
            popularity: 9, 
            year: 2012, 
            img: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Typescript.svg', 
            description: 'Superset do JavaScript que adiciona tipagem estática.', 
        },
        { 
            id: 9, 
            name: 'AWS', 
            categoryId: 7, 
            levelId: 3, 
            popularity: 10, 
            year: 2006, 
            img: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg', 
            description: 'Plataforma de computação em nuvem da Amazon.',
        },
        { 
            id: 10, 
            name: 'Git', 
            categoryId: 8, 
            levelId: 1, 
            popularity: 10, 
            year: 2005, 
            img: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Git-logo.svg', 
            description: 'Sistema de controle de versão distribuído.', 
        },
    ],
    categories: [
        { id: 1, name: 'Programming Language' },
        { id: 2, name: 'Frontend Library' },
        { id: 3, name: 'Backend Runtime' },
        { id: 4, name: 'DevOps Tool' },
        { id: 5, name: 'Database' },
        { id: 6, name: 'Machine Learning' },
        { id: 7, name: 'Cloud Computing' },
        { id: 8, name: 'Version Control' },
    ],
    levels: [
        { id: 1, name: 'Beginner Friendly' },
        { id: 2, name: 'Intermediate' },
        { id: 3, name: 'Advanced' },
        { id: 4, name: 'Expert' },
    ],
}

module.exports = data;