// Mensagens de coleta por idioma (mesmo mecanismo do MENU_LANG do menu). Português sem acentos.

export const ITEM_TEXT = {
  en: {
    // Etapa 20: portas de chave (mensagem no mesmo lugar das de coleta).
    needBlueKey: 'You need a blue key to open this door.',
    needYellowKey: 'You need a yellow key to open this door.',
    needRedKey: 'You need a red key to open this door.',
    stimpack: 'Picked up a stimpack.',
    medikit: 'Picked up a medikit.',
    healthBonus: 'Picked up a health bonus.',
    soulsphere: 'Supercharge!',
    megasphere: 'MegaSphere!',
    armorBonus: 'Picked up an armor bonus.',
    greenArmor: 'Picked up the armor.',
    blueArmor: 'Picked up the MegaArmor!',
    clip: 'Picked up a clip.',
    ammoBox: 'Picked up a box of bullets.',
    shells: 'Picked up 4 shotgun shells.',
    shellBox: 'Picked up a box of shotgun shells.',
    rocket: 'Picked up a rocket.',
    rocketBox: 'Picked up a box of rockets.',
    cell: 'Picked up an energy cell.',
    cellPack: 'Picked up an energy cell pack.',
    backpack: 'Picked up a backpack full of ammo!',
    blueCard: 'Picked up a blue keycard.',
    yellowCard: 'Picked up a yellow keycard.',
    redCard: 'Picked up a red keycard.',
    blueSkull: 'Picked up a blue skull key.',
    yellowSkull: 'Picked up a yellow skull key.',
    redSkull: 'Picked up a red skull key.',
    shotgun: 'You got the shotgun!',
    chaingun: 'You got the chaingun!',
    rocketLauncher: 'You got the rocket launcher!',
    plasma: 'You got the plasma gun!',
    bfg: 'You got the BFG9000! Oh, yes.',
    chainsaw: 'A chainsaw! Find some meat!',
  },
  pt: {
    needBlueKey: 'VOCE PRECISA DE UMA CHAVE AZUL PARA ABRIR ESTA PORTA.',
    needYellowKey: 'VOCE PRECISA DE UMA CHAVE AMARELA PARA ABRIR ESTA PORTA.',
    needRedKey: 'VOCE PRECISA DE UMA CHAVE VERMELHA PARA ABRIR ESTA PORTA.',
    stimpack: 'Pegou um estimulante.',
    medikit: 'Pegou um kit medico.',
    healthBonus: 'Pegou um bonus de vida.',
    soulsphere: 'Supercarga!',
    megasphere: 'Megaesfera!',
    armorBonus: 'Pegou um bonus de armadura.',
    greenArmor: 'Pegou a armadura.',
    blueArmor: 'Pegou a megaarmadura!',
    clip: 'Pegou um pente de balas.',
    ammoBox: 'Pegou uma caixa de balas.',
    shells: 'Pegou 4 cartuchos.',
    shellBox: 'Pegou uma caixa de cartuchos.',
    rocket: 'Pegou um foguete.',
    rocketBox: 'Pegou uma caixa de foguetes.',
    cell: 'Pegou uma celula de energia.',
    cellPack: 'Pegou um pacote de celulas de energia.',
    backpack: 'Pegou uma mochila cheia de municao!',
    blueCard: 'Pegou um cartao azul.',
    yellowCard: 'Pegou um cartao amarelo.',
    redCard: 'Pegou um cartao vermelho.',
    blueSkull: 'Pegou uma chave-caveira azul.',
    yellowSkull: 'Pegou uma chave-caveira amarela.',
    redSkull: 'Pegou uma chave-caveira vermelha.',
    shotgun: 'Voce pegou a espingarda!',
    chaingun: 'Voce pegou a metralhadora!',
    rocketLauncher: 'Voce pegou o lanca-foguetes!',
    plasma: 'Voce pegou a arma de plasma!',
    bfg: 'Voce pegou a BFG9000! Ah, sim.',
    chainsaw: 'Uma motosserra! Ache carne!',
  },
};
