export default [
    {
        files: ['**/*.js', '**/*.mjs'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                // Navegador e DOM
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                console: 'readonly',
                performance: 'readonly',
                fetch: 'readonly',
                localStorage: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                Blob: 'readonly',
                Event: 'readonly',
                KeyboardEvent: 'readonly',
                MouseEvent: 'readonly',
                HTMLElement: 'readonly',
                HTMLInputElement: 'readonly',
                Image: 'readonly',
                ImageData: 'readonly',
                alert: 'readonly',

                // WebGPU
                GPUDevice: 'readonly',
                GPUBufferUsage: 'readonly',
                GPUTextureUsage: 'readonly',
                GPUShaderStage: 'readonly',
                GPUMapMode: 'readonly',
                GPUColorWrite: 'readonly',
                GPUValidationError: 'readonly',
                GPUError: 'readonly',
                GPURenderPipeline: 'readonly',
                GPUComputePipeline: 'readonly',
                GPUShaderModule: 'readonly',
                GPUBindGroup: 'readonly',
                GPUBindGroupLayout: 'readonly',
                GPUTexture: 'readonly',
                GPUBuffer: 'readonly',
                GPUCanvasContext: 'readonly',

                // Node.js (tools e server)
                process: 'readonly',
                Buffer: 'readonly',
            },
        },
        rules: {
            'no-undef': 'error',
            'no-redeclare': 'error',
            'no-use-before-define': ['error', { variables: true, functions: false }],
            'block-scoped-var': 'error',
            'no-const-assign': 'error',
            'no-unreachable': 'error',
            'no-dupe-keys': 'error',
            'no-unused-vars': 'warn',
        },
    },
];
