// Textos do menu por idioma. Único lugar com texto do menu; os acentos são removidos no desenho.

export const MENU_LANG = 'en'; // 'en' ou 'pt'

export const MENU_TEXT = {
  en: {
    // No inglês, os três itens do menu principal usam os rótulos gráficos do WAD;
    // estes textos só aparecem se o rótulo gráfico faltar.
    newGame: 'NEW GAME',
    options: 'OPTIONS',
    readThis: 'READ THIS!',
    visualMode: 'VISUAL',
    crt: 'CRT',
    lighting: 'LIGHTING',
    fullscreen: 'FULLSCREEN',
    sfxVolumeLevel: 'SFX VOLUME',
    extras: 'EXTRAS',
    extrasTitle: 'EXTRAS',
    mouseSensitivityLevel: 'MOUSE SENSITIVITY',
    flySpeedLevel: 'SPEED',
    particles: 'PARTICLES',
    particleTuning: 'PARTICLE TUNING',
    sprites: 'SPRITES',
    moveMode: 'MOVEMENT',
    walk: 'WALK',
    fly: 'FLY',
    debug: 'DEBUG',
    textured: 'TEXTURES',
    sectorColors: 'SECTOR COLORS',
    culling: 'BACKFACE CULLING',
    skyTest: 'SKY TEST',
    hud: 'HUD',
    reset: 'RESET DEFAULTS',
    healthUp: 'HEALTH +10',
    damage10: 'DAMAGE 10',
    damage25: 'DAMAGE 25',
    godMode: 'GOD MODE',
    killPlayer: 'KILL PLAYER',
    screenFlashes: 'FLASHES',
    restartPrompt: 'PRESS USE (E) OR CLICK TO RESTART',
    openAllDoors: 'OPEN ALL DOORS',
    finishLevel: 'FINISH LEVEL',
    // Tela de estatísticas (etapa 20).
    statsFinished: 'FINISHED',
    statsSecret: 'SECRET EXIT',
    statsKills: 'KILLS',
    statsItems: 'ITEMS',
    statsTime: 'TIME',
    statsFooter: 'PRESS USE (E) OR CLICK TO PLAY AGAIN',
    armorUp: 'ARMOR +25',
    ammoUp: 'AMMO +10',
    resetStats: 'RESET STATS',
    gameDebug: 'GAME DEBUG',
    gameDebugTitle: 'GAME DEBUG',
    monsterDebug: 'MONSTER DEBUG',
    monsterDebugTitle: 'MONSTER DEBUG',
    monsterAI: 'MONSTER AI',
    noTarget: 'NO TARGET',
    resetMonsters: 'RESET MONSTERS',
    killAll: 'KILL ALL MONSTERS',
    giveKeys: 'GIVE ALL KEYS',
    giveWeapons: 'GIVE ALL WEAPONS',
    giveAmmo: 'GIVE AMMO',
    on: 'ON',
    off: 'OFF',
    retro: 'RETRO',
    moderno: 'MODERN',
    debugTitle: 'DEBUG',
    controlsTitle: 'CONTROLS',
    helpFooter: 'ESC OR ENTER TO RETURN',
    // Com mais de uma página ({page} = "1/2"); setas esquerda e direita também mudam de página.
    helpFooterPaged: 'PAGE {page}  ENTER: NEXT  ESC: BACK',
    clickToResume: 'CLICK TO RESUME',
    escKey: 'ESC',
    escAction: 'MENU',
    // Nomes curtos das ações de ACTION_KEYS (tela READ THIS!).
    actions: {
      forward: 'FORWARD', back: 'BACKWARD', left: 'STRAFE LEFT', right: 'STRAFE RIGHT',
      up: 'FLY UP', down: 'FLY DOWN', run: 'RUN', fullscreen: 'FULLSCREEN', help: 'HELP',
      lighting: 'LIGHTING', crt: 'CRT', visualMode: 'VISUAL MODE', hud: 'HUD',
      sensDown: 'MOUSE SENS -', sensUp: 'MOUSE SENS +', speedDown: 'SPEED -', speedUp: 'SPEED +',
      particles: 'PARTICLES', tuning: 'TUNING PANEL', sprites: 'SPRITES', toggleMoveMode: 'WALK / FLY',
      fire: 'FIRE', fireMouse: 'FIRE', toggleMute: 'MUTE', use: 'USE / RESTART',
    },
    // Linha única das setas (ações do grupo 'tuning') na tela READ THIS!.
    arrowsKey: 'ARROWS',
    arrowsAction: 'TURN (TUNING)',
    // Linhas únicas das armas (1 a 7; só 1 a 5 utilizáveis) e da roda do mouse.
    weaponsKey: '1 TO 5',
    weaponsAction: 'WEAPONS',
    wheelKey: 'WHEEL',
    wheelAction: 'CYCLE WEAPON',
    // Rótulos de tecla traduzidos (o resto usa o rótulo de ACTION_KEYS).
    keyLabels: { Space: 'SPACE', Mouse0: 'MOUSE1' },
  },
  pt: {
    newGame: 'NOVO JOGO',
    options: 'OPÇÕES',
    readThis: 'AJUDA',
    visualMode: 'VISUAL',
    crt: 'CRT',
    lighting: 'ILUMINAÇÃO',
    fullscreen: 'TELA CHEIA',
    sfxVolumeLevel: 'VOLUME DOS EFEITOS',
    extras: 'EXTRAS',
    extrasTitle: 'EXTRAS',
    mouseSensitivityLevel: 'SENSIBILIDADE DO MOUSE',
    flySpeedLevel: 'VELOCIDADE',
    particles: 'PARTICULAS',
    particleTuning: 'AJUSTE DE PARTICULAS',
    sprites: 'SPRITES',
    moveMode: 'MOVIMENTO',
    walk: 'ANDAR',
    fly: 'VOAR',
    debug: 'DEPURAÇÃO',
    textured: 'TEXTURAS',
    sectorColors: 'COR POR SETOR',
    culling: 'CULLING DE FACES',
    skyTest: 'TESTE DO CÉU',
    hud: 'HUD',
    reset: 'RESTAURAR PADRÕES',
    healthUp: 'VIDA +10',
    damage10: 'DANO 10',
    damage25: 'DANO 25',
    godMode: 'MODO DEUS',
    killPlayer: 'MATAR JOGADOR',
    screenFlashes: 'FLASHES',
    restartPrompt: 'APERTE E OU CLIQUE PARA REINICIAR',
    openAllDoors: 'ABRIR TODAS AS PORTAS',
    finishLevel: 'TERMINAR FASE',
    statsFinished: 'CONCLUIDA',
    statsSecret: 'SAIDA SECRETA',
    statsKills: 'MORTES',
    statsItems: 'ITENS',
    statsTime: 'TEMPO',
    statsFooter: 'APERTE E OU CLIQUE PARA JOGAR DE NOVO',
    armorUp: 'ARMADURA +25',
    ammoUp: 'MUNICAO +10',
    resetStats: 'REINICIAR STATUS',
    gameDebug: 'DEPURACAO DO JOGO',
    gameDebugTitle: 'DEPURACAO DO JOGO',
    monsterDebug: 'DEPURACAO DE MONSTROS',
    monsterDebugTitle: 'MONSTROS',
    monsterAI: 'IA DOS MONSTROS',
    noTarget: 'SEM ALVO',
    resetMonsters: 'REINICIAR MONSTROS',
    killAll: 'MATAR TODOS OS MONSTROS',
    giveKeys: 'DAR TODAS AS CHAVES',
    giveWeapons: 'DAR TODAS AS ARMAS',
    giveAmmo: 'DAR MUNICAO',
    on: 'SIM',
    off: 'NÃO',
    retro: 'RETRO',
    moderno: 'MODERNO',
    debugTitle: 'DEPURAÇÃO',
    controlsTitle: 'CONTROLES',
    helpFooter: 'ESC OU ENTER PARA VOLTAR',
    helpFooterPaged: 'PAGINA {page}  ENTER: SEGUE  ESC: VOLTA',
    clickToResume: 'CLIQUE PARA CONTINUAR',
    escKey: 'ESC',
    escAction: 'MENU',
    actions: {
      forward: 'FRENTE', back: 'TRÁS', left: 'ESQUERDA', right: 'DIREITA',
      up: 'SUBIR', down: 'DESCER', run: 'CORRER', fullscreen: 'TELA CHEIA', help: 'AJUDA',
      lighting: 'ILUMINAÇÃO', crt: 'CRT', visualMode: 'MODO VISUAL', hud: 'HUD',
      sensDown: 'SENSIBIL. -', sensUp: 'SENSIBIL. +', speedDown: 'VELOC. -', speedUp: 'VELOC. +',
      particles: 'PARTICULAS', tuning: 'CALIBRAGEM', sprites: 'SPRITES', toggleMoveMode: 'ANDAR / VOAR',
      fire: 'ATIRAR', fireMouse: 'ATIRAR', toggleMute: 'MUDO', use: 'USAR/REINICIO',
    },
    arrowsKey: 'SETAS',
    arrowsAction: 'GIRAR CAMERA',
    weaponsKey: '1 A 5',
    weaponsAction: 'ARMAS',
    wheelKey: 'RODA',
    wheelAction: 'TROCAR ARMA',
    keyLabels: { Mouse0: 'MOUSE1' },
  },
};
