// Textos do menu por idioma. Único lugar com texto do menu; os acentos são removidos no desenho.

export const MENU_LANG = 'en'; // 'en' ou 'pt'

export const MENU_TEXT = {
  en: {
    // No inglês, os três itens do menu principal usam os rótulos gráficos do WAD;
    // estes textos só aparecem se o rótulo gráfico faltar.
    newGame: 'NEW GAME',
    options: 'OPTIONS',
    readThis: 'READ THIS!',
    visualMode: 'VISUAL',
    crt: 'CRT',
    lighting: 'LIGHTING',
    fullscreen: 'FULLSCREEN',
    sfxVolumeLevel: 'SFX VOLUME',
    extras: 'EXTRAS',
    extrasTitle: 'EXTRAS',
    mouseSensitivityLevel: 'MOUSE SENSITIVITY',
    flySpeedLevel: 'SPEED',
    particles: 'PARTICLES',
    particleTuning: 'PARTICLE TUNING',
    sprites: 'SPRITES',
    moveMode: 'MOVEMENT',
    walk: 'WALK',
    fly: 'FLY',
    debug: 'DEBUG',
    textured: 'TEXTURES',
    sectorColors: 'SECTOR COLORS',
    culling: 'BACKFACE CULLING',
    skyTest: 'SKY TEST',
    hud: 'HUD',
    reset: 'RESET DEFAULTS',
    healthUp: 'HEALTH +10',
    damage10: 'DAMAGE 10',
    damage25: 'DAMAGE 25',
    godMode: 'GOD MODE',
    killPlayer: 'KILL PLAYER',
    screenFlashes: 'FLASHES',
    restartPrompt: 'PRESS USE (E) OR CLICK TO RESTART',
    // Etapa 22: créditos, copiados de CREDITS.md e src/shaders/external/particles/SOURCE.txt (o que
    // falta lá aparece como VER CREDITS.MD). A fonte STCFN só tem maiúsculas.
    credits: 'CREDITS',
    creditsTitle: 'CREDITS',
    creditsPages: [
      ['FREEDOOM', 'PROJECT: FREEDOOM', 'FILE: ASSETS/FREEDOOM1.WAD', 'SITE: VER CREDITS.MD', 'LICENSE: VER CREDITS.MD', '',
        'CRT SHADER', 'PUBLIC DOMAIN CRT STYLED', 'SCAN-LINE SHADER', 'AUTHOR: TIMOTHY LOTTES', 'SHADERTOY: TIMOTHYLOTTES',
        'LICENSE: PUBLIC DOMAIN', 'SOURCE: HTTPS://WWW.SHADERTOY.COM/', 'VIEW/XSJSZR'],
      ['PARTICLES', 'PROJECT: WEBGPU SAMPLES', '(WEBGPU/WEBGPU-SAMPLES)', 'EXAMPLE: PARTICLES', 'AUTHORS: WEBGPU SAMPLES',
        'CONTRIBUTORS', 'LICENSE: BSD-3-CLAUSE', 'SOURCE: HTTPS://GITHUB.COM/', 'WEBGPU/WEBGPU-SAMPLES/TREE/', 'MAIN/SAMPLE/PARTICLES'],
    ],
    // Automapa (etapa 22): linhas da ajuda.
    amFollowKey: 'F', amFollow: 'MAP: FOLLOW',
    amGridKey: 'G', amGrid: 'MAP: GRID',
    amZoomKey: '+ -', amZoom: 'MAP: ZOOM',
    amBigKey: '0', amBig: 'MAP: WHOLE',
    amPan: 'MAP: PAN',
    openAllDoors: 'OPEN ALL DOORS',
    finishLevel: 'FINISH LEVEL',
    // Tela de estatísticas (etapa 20).
    statsFinished: 'FINISHED',
    statsSecret: 'SECRET EXIT',
    statsKills: 'KILLS',
    statsItems: 'ITEMS',
    statsTime: 'TIME',
    statsFooter: 'PRESS USE (E) OR CLICK TO PLAY AGAIN',
    armorUp: 'ARMOR +25',
    ammoUp: 'AMMO +10',
    resetStats: 'RESET STATS',
    gameDebug: 'GAME DEBUG',
    gameDebugTitle: 'GAME DEBUG',
    monsterDebug: 'MONSTER DEBUG',
    monsterDebugTitle: 'MONSTER DEBUG',
    monsterAI: 'MONSTER AI',
    noTarget: 'NO TARGET',
    resetMonsters: 'RESET MONSTERS',
    killAll: 'KILL ALL MONSTERS',
    // Etapa 23: troca de nível.
    levelDebug: 'LEVEL DEBUG',
    levelDebugTitle: 'LEVEL DEBUG',
    reloadLevel: 'RELOAD LEVEL',
    nextMap: 'NEXT MAP',
    prevMap: 'PREV MAP',
    // NEW GAME (etapa 23): no inglês aparecem os gráficos do WAD; estes textos são a reserva.
    episodeTitle: 'WHICH EPISODE?',
    episode1: 'EPISODE 1', episode2: 'EPISODE 2', episode3: 'EPISODE 3', episode4: 'EPISODE 4',
    skillTitle: 'CHOOSE SKILL LEVEL:',
    skill1: 'VERY EASY', skill2: 'EASY', skill3: 'MEDIUM', skill4: 'HARD', skill5: 'NIGHTMARE!',
    skillShort: ['', 'VERY EASY', 'EASY', 'MEDIUM', 'HARD', 'NIGHTMARE'],
    nightmareConfirm: 'NIGHTMARE IS NOT FAIR:\nMONSTERS ARE FASTER AND COME BACK.\n\nARE YOU SURE?\n\nY OR ENTER: YES    N OR ESC: NO',
    finalePress: 'PRESS A KEY',
    // Etapa 23: textos de fim de episódio (próprios do projeto).
    finaleText: {
      1: 'THE OUTPOST IS QUIET AT LAST.\nTHE LAST GATE GROANS SHUT BEHIND\nYOU, BUT THE SILENCE DOES NOT\nFEEL LIKE PEACE. SOMETHING ON\nTHE OTHER SIDE IS STILL AWAKE.\n\nTHE ROAD GOES ON.',
      2: 'THE TOWERS HAVE STOPPED HUMMING.\nSMOKE DRIFTS OVER BROKEN STEEL\nAND THE MACHINES ARE STILL.\nYOU WALK ON, TIRED, TOWARD A\nRED HORIZON THAT NEVER SETS.\n\nTHE ROAD GOES DOWN.',
      3: 'THE GROUND STOPS BURNING.\nWHAT RULED THIS PLACE LIES STILL\nAT YOUR FEET, AND A PATH BACK\nOPENS IN THE ASH. HOME IS FAR,\nBUT FOR THE FIRST TIME IT FEELS\nCLOSE ENOUGH TO REACH.',
      4: 'IT IS OVER, FOR NOW.\nTHE LAST OF THEM FALLS AND THE\nWIND CARRIES THE ASH AWAY.\nYOU KEEP YOUR WEAPON CLOSE\nANYWAY: SOME DOORS NEVER STAY\nSHUT FOR LONG.',
    },
    loading: 'LOADING...',
    loadFailed: 'FAILED TO LOAD',
    giveKeys: 'GIVE ALL KEYS',
    giveWeapons: 'GIVE ALL WEAPONS',
    giveAmmo: 'GIVE AMMO',
    on: 'ON',
    off: 'OFF',
    retro: 'RETRO',
    moderno: 'MODERN',
    debugTitle: 'DEBUG',
    controlsTitle: 'CONTROLS',
    helpFooter: 'ESC OR ENTER TO RETURN',
    // Com mais de uma página ({page} = "1/2"); setas esquerda e direita também mudam de página.
    helpFooterPaged: 'PAGE {page}  ENTER: NEXT  ESC: BACK',
    clickToResume: 'CLICK TO RESUME',
    escKey: 'ESC',
    escAction: 'MENU',
    // Nomes curtos das ações de ACTION_KEYS (tela READ THIS!).
    actions: {
      forward: 'FORWARD', back: 'BACKWARD', left: 'STRAFE LEFT', right: 'STRAFE RIGHT',
      up: 'FLY UP', down: 'FLY DOWN', run: 'RUN', fullscreen: 'FULLSCREEN', help: 'HELP',
      lighting: 'LIGHTING', crt: 'CRT', visualMode: 'VISUAL MODE', hud: 'HUD',
      sensDown: 'MOUSE SENS -', sensUp: 'MOUSE SENS +', speedDown: 'SPEED -', speedUp: 'SPEED +',
      particles: 'PARTICLES', tuning: 'TUNING PANEL', sprites: 'SPRITES', toggleMoveMode: 'WALK / FLY',
      fire: 'FIRE', fireMouse: 'FIRE', toggleMute: 'MUTE', use: 'USE / RESTART', toggleAutomap: 'AUTOMAP',
    },
    // Linha única das setas (ações do grupo 'tuning') na tela READ THIS!.
    arrowsKey: 'ARROWS',
    arrowsAction: 'TURN (TUNING)',
    // Linhas únicas das armas (1 a 7; só 1 a 5 utilizáveis) e da roda do mouse.
    weaponsKey: '1 TO 5',
    weaponsAction: 'WEAPONS',
    wheelKey: 'WHEEL',
    wheelAction: 'CYCLE WEAPON',
    // Rótulos de tecla traduzidos (o resto usa o rótulo de ACTION_KEYS).
    keyLabels: { Space: 'SPACE', Mouse0: 'MOUSE1' },
  },
  pt: {
    newGame: 'NOVO JOGO',
    options: 'OPÇÕES',
    readThis: 'AJUDA',
    visualMode: 'VISUAL',
    crt: 'CRT',
    lighting: 'ILUMINAÇÃO',
    fullscreen: 'TELA CHEIA',
    sfxVolumeLevel: 'VOLUME DOS EFEITOS',
    extras: 'EXTRAS',
    extrasTitle: 'EXTRAS',
    mouseSensitivityLevel: 'SENSIBILIDADE DO MOUSE',
    flySpeedLevel: 'VELOCIDADE',
    particles: 'PARTICULAS',
    particleTuning: 'AJUSTE DE PARTICULAS',
    sprites: 'SPRITES',
    moveMode: 'MOVIMENTO',
    walk: 'ANDAR',
    fly: 'VOAR',
    debug: 'DEPURAÇÃO',
    textured: 'TEXTURAS',
    sectorColors: 'COR POR SETOR',
    culling: 'CULLING DE FACES',
    skyTest: 'TESTE DO CÉU',
    hud: 'HUD',
    reset: 'RESTAURAR PADRÕES',
    healthUp: 'VIDA +10',
    damage10: 'DANO 10',
    damage25: 'DANO 25',
    godMode: 'MODO DEUS',
    killPlayer: 'MATAR JOGADOR',
    screenFlashes: 'FLASHES',
    restartPrompt: 'APERTE E OU CLIQUE PARA REINICIAR',
    credits: 'CREDITOS',
    creditsTitle: 'CREDITOS',
    creditsPages: [
      ['FREEDOOM', 'PROJETO: FREEDOOM', 'ARQUIVO: ASSETS/FREEDOOM1.WAD', 'SITE: VER CREDITS.MD', 'LICENCA: VER CREDITS.MD', '',
        'SHADER CRT', 'PUBLIC DOMAIN CRT STYLED', 'SCAN-LINE SHADER', 'AUTOR: TIMOTHY LOTTES', 'SHADERTOY: TIMOTHYLOTTES',
        'LICENCA: DOMINIO PUBLICO', 'FONTE: HTTPS://WWW.SHADERTOY.COM/', 'VIEW/XSJSZR'],
      ['PARTICULAS', 'PROJETO: WEBGPU SAMPLES', '(WEBGPU/WEBGPU-SAMPLES)', 'EXEMPLO: PARTICLES', 'AUTORES: WEBGPU SAMPLES',
        'CONTRIBUTORS', 'LICENCA: BSD-3-CLAUSE', 'FONTE: HTTPS://GITHUB.COM/', 'WEBGPU/WEBGPU-SAMPLES/TREE/', 'MAIN/SAMPLE/PARTICLES'],
    ],
    amFollowKey: 'F', amFollow: 'MAPA: SEGUIR',
    amGridKey: 'G', amGrid: 'MAPA: GRADE',
    amZoomKey: '+ -', amZoom: 'MAPA: ZOOM',
    amBigKey: '0', amBig: 'MAPA: INTEIRO',
    amPan: 'MAPA: MOVER',
    openAllDoors: 'ABRIR TODAS AS PORTAS',
    finishLevel: 'TERMINAR FASE',
    statsFinished: 'CONCLUIDA',
    statsSecret: 'SAIDA SECRETA',
    statsKills: 'MORTES',
    statsItems: 'ITENS',
    statsTime: 'TEMPO',
    statsFooter: 'APERTE E OU CLIQUE PARA JOGAR DE NOVO',
    armorUp: 'ARMADURA +25',
    ammoUp: 'MUNICAO +10',
    resetStats: 'REINICIAR STATUS',
    gameDebug: 'DEPURACAO DO JOGO',
    gameDebugTitle: 'DEPURACAO DO JOGO',
    monsterDebug: 'DEPURACAO DE MONSTROS',
    monsterDebugTitle: 'MONSTROS',
    monsterAI: 'IA DOS MONSTROS',
    noTarget: 'SEM ALVO',
    resetMonsters: 'REINICIAR MONSTROS',
    killAll: 'MATAR TODOS OS MONSTROS',
    levelDebug: 'DEPURACAO DE FASES',
    levelDebugTitle: 'FASES',
    reloadLevel: 'RECARREGAR FASE',
    nextMap: 'PROXIMO MAPA',
    prevMap: 'MAPA ANTERIOR',
    episodeTitle: 'QUAL EPISODIO?',
    episode1: 'EPISODIO 1', episode2: 'EPISODIO 2', episode3: 'EPISODIO 3', episode4: 'EPISODIO 4',
    skillTitle: 'ESCOLHA A DIFICULDADE:',
    skill1: 'MUITO FACIL', skill2: 'FACIL', skill3: 'MEDIO', skill4: 'DIFICIL', skill5: 'PESADELO!',
    skillShort: ['', 'MUITO FACIL', 'FACIL', 'MEDIO', 'DIFICIL', 'PESADELO'],
    nightmareConfirm: 'O PESADELO NAO E JUSTO:\nMONSTROS MAIS RAPIDOS QUE VOLTAM.\n\nTEM CERTEZA?\n\nS, Y OU ENTER: SIM    N OU ESC: NAO',
    finalePress: 'APERTE UMA TECLA',
    // Etapa 23: textos de fim de episódio (próprios do projeto).
    finaleText: {
      1: 'O POSTO AVANCADO FINALMENTE SE\nCALOU. O ULTIMO PORTAO SE FECHA\nATRAS DE VOCE, MAS O SILENCIO\nNAO PARECE PAZ. ALGO DO OUTRO\nLADO AINDA ESTA ACORDADO.\n\nA ESTRADA CONTINUA.',
      2: 'AS TORRES PARARAM DE ZUMBIR.\nA FUMACA PASSA SOBRE O ACO\nQUEBRADO E AS MAQUINAS SE\nCALARAM. VOCE SEGUE, CANSADO,\nRUMO A UM HORIZONTE VERMELHO.\n\nA ESTRADA DESCE.',
      3: 'O CHAO PAROU DE QUEIMAR.\nO QUE MANDAVA AQUI ESTA CAIDO\nAOS SEUS PES, E UM CAMINHO DE\nVOLTA SE ABRE NAS CINZAS. A CASA\nESTA LONGE, MAS PELA PRIMEIRA\nVEZ PARECE POSSIVEL CHEGAR.',
      4: 'ACABOU, POR ENQUANTO.\nO ULTIMO DELES CAI E O VENTO\nLEVA AS CINZAS EMBORA. MESMO\nASSIM, VOCE MANTEM A ARMA POR\nPERTO: ALGUMAS PORTAS NUNCA\nFICAM FECHADAS POR MUITO TEMPO.',
    },
    loading: 'CARREGANDO...',
    loadFailed: 'FALHA AO CARREGAR',
    giveKeys: 'DAR TODAS AS CHAVES',
    giveWeapons: 'DAR TODAS AS ARMAS',
    giveAmmo: 'DAR MUNICAO',
    on: 'SIM',
    off: 'NÃO',
    retro: 'RETRO',
    moderno: 'MODERNO',
    debugTitle: 'DEPURAÇÃO',
    controlsTitle: 'CONTROLES',
    helpFooter: 'ESC OU ENTER PARA VOLTAR',
    helpFooterPaged: 'PAGINA {page}  ENTER: SEGUE  ESC: VOLTA',
    clickToResume: 'CLIQUE PARA CONTINUAR',
    escKey: 'ESC',
    escAction: 'MENU',
    actions: {
      forward: 'FRENTE', back: 'TRÁS', left: 'ESQUERDA', right: 'DIREITA',
      up: 'SUBIR', down: 'DESCER', run: 'CORRER', fullscreen: 'TELA CHEIA', help: 'AJUDA',
      lighting: 'ILUMINAÇÃO', crt: 'CRT', visualMode: 'MODO VISUAL', hud: 'HUD',
      sensDown: 'SENSIBIL. -', sensUp: 'SENSIBIL. +', speedDown: 'VELOC. -', speedUp: 'VELOC. +',
      particles: 'PARTICULAS', tuning: 'CALIBRAGEM', sprites: 'SPRITES', toggleMoveMode: 'ANDAR / VOAR',
      fire: 'ATIRAR', fireMouse: 'ATIRAR', toggleMute: 'MUDO', use: 'USAR/REINICIO', toggleAutomap: 'AUTOMAPA',
    },
    arrowsKey: 'SETAS',
    arrowsAction: 'GIRAR CAMERA',
    weaponsKey: '1 A 5',
    weaponsAction: 'ARMAS',
    wheelKey: 'RODA',
    wheelAction: 'TROCAR ARMA',
    keyLabels: { Mouse0: 'MOUSE1' },
  },
};
